# Generated by Django 5.1.5 on 2025-03-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_gender_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.fieldofstudy'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_list', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.module')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.fieldofstudy')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.module')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
